### ISSUE TITLE
بالتوفيق إن شاء الله، ومبارك سلفاً :)

### ISSUE THREAD

**Issue by AAlakkad** [forabi/thesis#1]

**Comment by forabi** [comment]
شكرًا جزيلًا عمار! :)

**Comment by AAlakkad** [comment]
هل تستخدم محرر [Stackedit](https://stackedit.io/editor) أم غيره؟

**Comment by forabi** [comment]
بل gedit في GNOME

**Comment by AAlakkad** [comment]
هل هو جيّد بدعم اتجاه العربية إن كان بداخلها شيء بالإنكليزية؟
عذراً على التطفّل :smile:

**Comment by forabi** [comment]
نعم، لا بأس به، فهو يغير اتجاه كل سطر بحسب حرفه الأول. في الحقيقة هو أفضل
ما وجدته في هذه النقطة.

**Comment by AAlakkad** [comment]
سأقوم بتجربته، شكراً لك :)
